services:
  anirra:
    container_name: anirra
    image: jpyles0524/anirra:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: bash /start.sh
    env_file: .env
    environment:
      - APP_MODE=PROD
    volumes:
      - ./data:/project/data
      - ./config.yaml:/project/config.yaml
    ports:
      - 3000:3000
      - 8000:8000
