"""Added rating to anime

Revision ID: 14993209626a
Revises: b70465a54583
Create Date: 2025-04-22 18:09:34.053644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14993209626a'
down_revision: Union[str, None] = 'b70465a54583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_to_anime', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist_to_anime', 'rating')
    # ### end Alembic commands ###
