on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run-cypress-tests

  build:
    runs-on: ubuntu-latest
    needs: e2e-tests

    outputs:
      version: ${{ steps.set_version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        id: set_version
        run: |
          VERSION=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8)
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        uses: ./.github/actions/docker-image
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_repo: anirra
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: Dockerfile

  # test:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Test Python
  #       uses: ./.github/actions/test-python
  #       with:
  #         docker_image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ needs.build.outputs.version }}
